### ISSUE TITLE
Add a javascript version of the ecosystem diagram

### ISSUE THREAD

**Issue by gadomski** [stac-utils/.github#2]
Base it on this.

![image](https://github.com/stac-utils/.github/assets/58314/bf69473d-4c97-44d0-ada0-e0bb68346cb0)

**Comment by m-mohr** [comment]
Just found you can export from Google Slides so that it doesn't show "spelling errors":

![grafik](https://github.com/stac-utils/.github/assets/8262166/582ce932-7662-49a8-a465-82a0c265a252)
